HFA-34 feat(service): add config service
RandomUserIK/HomesFromArchitectsWebPage-frontend pull request #3
Opened 2021-03-14 17:41 UTC by trofoSK

2021-03-14 19:57 UTC, RandomUserIK requested changes

2021-03-14 19:57 UTC, RandomUserIK commented on src/app/services/configuration-service.ts
> +    super(naeConfig as ApplicationProperties);
naeConfig?

2021-03-14 19:57 UTC, RandomUserIK commented on src/app/resources/config.json
> +        "signup": "/auth/signup"
signup asi nepotrebujeme, kedze registraciu userov nebudeme riesit

2021-03-14 20:00 UTC, RandomUserIK approved these changes

2021-03-15 08:30 UTC, b0tka approved these changes

2021-03-15 08:34 UTC, b0tka approved these changes

2021-03-19 06:56 UTC, merged