Hfa 33 - Controllers for individual projects and photos
RandomUserIK/HomesFromArchitectsWebPage-frontend pull request #4
Opened 2021-03-18 18:36 UTC by trofoSK

2021-03-19 06:54 UTC, RandomUserIK requested changes

2021-03-19 06:54 UTC, RandomUserIK commented on src/app/admin/projects/interfaces/project-data.ts
> +export interface TextSections {
tu tiez potom nezabudni zmenit na `TextSection`

2021-03-20 19:12 UTC, MartinMiklovic commented on src/app/admin/projects/services/project-service.ts
> +  providedIn: 'root'
Kedže je táto servica spojená s záložkou projekty treba vytvoriť pre túto kategóriu zvlášť modul a nasledovne tam túto servicu vložiť do providers.

2021-03-21 16:39 UTC, RandomUserIK approved these changes

2021-03-22 20:35 UTC, closed without merging